const path = require("path");

const FILE_TYPES = {
  csv:        { extensions: [".csv"],                          category: "tabular", outputExt: ".csv",       description: "CSV Spreadsheet" },
  excel:      { extensions: [".xlsx", ".xls"],                 category: "tabular", outputExt: ".csv",       description: "Excel Spreadsheet" },
  tsv:        { extensions: [".tsv", ".tab"],                  category: "tabular", outputExt: ".csv",       description: "TSV Spreadsheet" },
  json:       { extensions: [".json"],                         category: "data",    outputExt: ".json",      description: "JSON Data" },
  xml:        { extensions: [".xml"],                          category: "data",    outputExt: ".xml",       description: "XML Data" },
  yaml:       { extensions: [".yaml", ".yml"],                 category: "data",    outputExt: ".yaml",      description: "YAML Data" },
  sql:        { extensions: [".sql"],                          category: "data",    outputExt: ".sql",       description: "SQL Script" },
  graphql:    { extensions: [".graphql", ".gql"],              category: "data",    outputExt: ".graphql",   description: "GraphQL Schema" },
  proto:      { extensions: [".proto"],                        category: "data",    outputExt: ".proto",     description: "Protobuf Schema" },
  html:       { extensions: [".html", ".htm"],                 category: "markup",  outputExt: ".html",      description: "HTML Document" },
  css:        { extensions: [".css"],                          category: "markup",  outputExt: ".css",       description: "CSS Stylesheet" },
  scss:       { extensions: [".scss"],                         category: "markup",  outputExt: ".scss",      description: "SCSS Stylesheet" },
  sass:       { extensions: [".sass"],                         category: "markup",  outputExt: ".sass",      description: "Sass Stylesheet" },
  less:       { extensions: [".less"],                         category: "markup",  outputExt: ".less",      description: "Less Stylesheet" },
  markdown:   { extensions: [".md", ".markdown"],              category: "markup",  outputExt: ".md",        description: "Markdown Document" },
  svelte:     { extensions: [".svelte"],                       category: "markup",  outputExt: ".svelte",    description: "Svelte Component" },
  vue:        { extensions: [".vue"],                          category: "markup",  outputExt: ".vue",       description: "Vue Component" },
  javascript: { extensions: [".js", ".mjs", ".cjs"],          category: "code",    outputExt: ".js",        description: "JavaScript" },
  typescript: { extensions: [".ts"],                           category: "code",    outputExt: ".ts",        description: "TypeScript" },
  tsx:        { extensions: [".tsx"],                          category: "code",    outputExt: ".tsx",       description: "TypeScript JSX" },
  jsx:        { extensions: [".jsx"],                          category: "code",    outputExt: ".jsx",       description: "JavaScript JSX" },
  python:     { extensions: [".py"],                           category: "code",    outputExt: ".py",        description: "Python" },
  ipynb:      { extensions: [".ipynb"],                        category: "data",    outputExt: ".ipynb",     description: "Jupyter Notebook" },
  c:          { extensions: [".c", ".h"],                      category: "code",    outputExt: ".c",         description: "C" },
  cpp:        { extensions: [".cpp", ".cc", ".cxx", ".hpp"],   category: "code",    outputExt: ".cpp",       description: "C++" },
  rust:       { extensions: [".rs"],                           category: "code",    outputExt: ".rs",        description: "Rust" },
  go:         { extensions: [".go"],                           category: "code",    outputExt: ".go",        description: "Go" },
  zig:        { extensions: [".zig"],                          category: "code",    outputExt: ".zig",       description: "Zig" },
  java:       { extensions: [".java"],                         category: "code",    outputExt: ".java",      description: "Java" },
  kotlin:     { extensions: [".kt", ".kts"],                   category: "code",    outputExt: ".kt",        description: "Kotlin" },
  scala:      { extensions: [".scala"],                        category: "code",    outputExt: ".scala",     description: "Scala" },
  groovy:     { extensions: [".groovy"],                       category: "code",    outputExt: ".groovy",    description: "Groovy" },
  clojure:    { extensions: [".clj", ".cljs"],                 category: "code",    outputExt: ".clj",       description: "Clojure" },
  csharp:     { extensions: [".cs"],                           category: "code",    outputExt: ".cs",        description: "C#" },
  fsharp:     { extensions: [".fs", ".fsx"],                   category: "code",    outputExt: ".fs",        description: "F#" },
  vb:         { extensions: [".vb"],                           category: "code",    outputExt: ".vb",        description: "Visual Basic" },
  php:        { extensions: [".php"],                          category: "code",    outputExt: ".php",       description: "PHP" },
  ruby:       { extensions: [".rb"],                           category: "code",    outputExt: ".rb",        description: "Ruby" },
  perl:       { extensions: [".pl", ".pm"],                    category: "code",    outputExt: ".pl",        description: "Perl" },
  lua:        { extensions: [".lua"],                          category: "code",    outputExt: ".lua",       description: "Lua" },
  r:          { extensions: [".r", ".R"],                      category: "code",    outputExt: ".r",         description: "R" },
  julia:      { extensions: [".jl"],                           category: "code",    outputExt: ".jl",        description: "Julia" },
  dart:       { extensions: [".dart"],                         category: "code",    outputExt: ".dart",      description: "Dart" },
  swift:      { extensions: [".swift"],                        category: "code",    outputExt: ".swift",     description: "Swift" },
  objc:       { extensions: [".m", ".mm"],                     category: "code",    outputExt: ".m",         description: "Objective-C" },
  elixir:     { extensions: [".ex", ".exs"],                   category: "code",    outputExt: ".ex",        description: "Elixir" },
  erlang:     { extensions: [".erl", ".hrl"],                  category: "code",    outputExt: ".erl",       description: "Erlang" },
  haskell:    { extensions: [".hs", ".lhs"],                   category: "code",    outputExt: ".hs",        description: "Haskell" },
  ocaml:      { extensions: [".ml", ".mli"],                   category: "code",    outputExt: ".ml",        description: "OCaml" },
  shell:      { extensions: [".sh", ".bash", ".zsh", ".fish"], category: "code",    outputExt: ".sh",        description: "Shell Script" },
  powershell: { extensions: [".ps1", ".psm1"],                 category: "code",    outputExt: ".ps1",       description: "PowerShell" },
  batch:      { extensions: [".bat", ".cmd"],                  category: "code",    outputExt: ".bat",       description: "Batch Script" },
  makefile:   { extensions: [".mk"],                           category: "code",    outputExt: ".mk",        description: "Makefile" },
  dockerfile: { extensions: [".dockerfile"],                   category: "code",    outputExt: ".dockerfile",description: "Dockerfile" },
  terraform:  { extensions: [".tf", ".tfvars"],                category: "code",    outputExt: ".tf",        description: "Terraform" },
  text:       { extensions: [".txt", ".log", ".text"],         category: "text",    outputExt: ".txt",       description: "Plain Text" },
  env:        { extensions: [".env"],                          category: "text",    outputExt: ".env",       description: "Environment Config" },
  ini:        { extensions: [".ini", ".cfg"],                  category: "text",    outputExt: ".ini",       description: "INI Config" },
  toml:       { extensions: [".toml"],                         category: "text",    outputExt: ".toml",      description: "TOML Config" },
  conf:       { extensions: [".conf"],                         category: "text",    outputExt: ".conf",      description: "​​​​​​​​​​​​​​​​
